import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Present in every page
function Header()
{
  return (
    <header>

      <div>
        <nav>
          <div>
            <Link href='/'>Home</Link>
          </div>
          
          <div>
            <Link href='/'>About Me</Link>
          </div>
          
          <div>
            <Link href='/'>Projects</Link>
          </div>
          
          <div>
            <Link href='/test'>TEST</Link>
          </div>
        </nav>
      </div>
    </header>
  )
}

// Main ROOT
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
